### ISSUE TITLE
Create a proxy?

### ISSUE THREAD

**Issue by Niels-P** [anvk/redux-portal-boilerplate#13]
How can I create a proxy within your boilerplate?
I'm trying to connect from my development environment to a separate server and get the following error message. 
> Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 403.

**Comment by anvk** [comment]
Of course!
I've added a commented out example. Take a look into `/webpack/dev.config.js` .You can setup as many proxy entries as you like when you run portal in *development* mode using webpack-dev-server.

So in my example any request which would be of type `<BASE_URL>/api/*` (where `BASE_URL` is `http://localhost:8080`, where dev setup is run be default in this project) will be replaced with `http://localhost:5000/api/*`

Let me know if you have any issues with it.

**Comment by Niels-P** [comment]
Thank you for the example Anvk! I've tried to add the proxy in the project like so:

> config.devServer = {
    contentBase: 'static/',
    historyApiFallback: true,
    proxy: {
        '/api/*': 'http://xxxAPIURLHERE.nl/'
    },
};

Now in the AuthApi I've putted the route in.

> export function authenticate(email = '', password = '') {
  return new Promise((resolve, reject) => {
    var user = null;
    request.post('/api/user/token')
        .timeout(timeout)
        .set('Accept', 'application/json')
        .set('Content-Type', 'application/json; charset=utf-8')
        .send({ email: email, password: password })
        .end(function (err, res) {
          if (err || !res.ok) {
              console.log(err);
              return reject('Your login details are in-correct.');
          } else {
            user = res.body;
            resolve({ ...user });
          }
        });
  });
}

Then I receive a 404.
> POST http://localhost:8080/api/user/token 404 (Not Found)
    at Request.<anonymous> (client.js:501)
    at Request.Emitter.emit (index.js:133)
    at XMLHttpRequest.xhr.onreadystatechange (client.js:772)

If I go to the browser to localhost:8080/api/user/token it also shows a 404. 
Any idea's?

**Comment by anvk** [comment]
You cannot view `POST` requests through browser. You can view only `GET` requests.
Use Postman, curl, Advanced Rest Client plugin for Chrome or whatever you fancy to ensure that your token endpoint is accessible and working.

Just ensure that your API endpoint works *before* you start using it in your UI.

Once your endpoint works you need to ensure that UI calls an *exact* working endpoint you have. For that double check in Network tab of your modern browser that the request is correct.
